package main

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

// ─────────────────────────────────────────────────────────────────────────────
// Zip helpers (shared by packager and the generated runner)
// ─────────────────────────────────────────────────────────────────────────────

// addFileToZip adds a single file to the zip archive under nameInZip.
func addFileToZip(zw *zip.Writer, srcPath, nameInZip string) error {
	src, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer src.Close()

	info, err := src.Stat()
	if err != nil {
		return err
	}

	header, err := zip.FileInfoHeader(info)
	if err != nil {
		return err
	}
	header.Name = nameInZip
	header.Method = zip.Deflate

	w, err := zw.CreateHeader(header)
	if err != nil {
		return err
	}
	_, err = io.Copy(w, src)
	return err
}

// addDirToZip recursively adds srcDir into the zip under prefix/.
// Symlinks are resolved to their targets (required for JRE bin/).
func addDirToZip(zw *zip.Writer, srcDir, prefix string) error {
	return filepath.WalkDir(srcDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(srcDir, path)
		if err != nil {
			return err
		}
		nameInZip := prefix + "/" + filepath.ToSlash(rel)

		if d.IsDir() {
			if !strings.HasSuffix(nameInZip, "/") {
				nameInZip += "/"
			}
			_, err = zw.Create(nameInZip)
			return err
		}

		// Resolve symlinks so the zip contains real files
		realPath, err := filepath.EvalSymlinks(path)
		if err != nil {
			realPath = path
		}

		info, err := os.Stat(realPath)
		if err != nil {
			return err
		}

		header, err := zip.FileInfoHeader(info)
		if err != nil {
			return err
		}
		header.Name = nameInZip
		header.Method = zip.Deflate
		header.SetMode(info.Mode())

		w, err := zw.CreateHeader(header)
		if err != nil {
			return err
		}

		f, err := os.Open(realPath)
		if err != nil {
			return err
		}
		defer f.Close()
		_, err = io.Copy(w, f)
		return err
	})
}

// buildPayloadZip creates an in-memory zip containing:
//
//	app.jar  (or app.war)
//	jre/     (minimal JRE)
//
// Returns the raw zip bytes and a hex SHA-256 of those bytes.
func buildPayloadZip(jarPath, jreDir string) ([]byte, string, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	jarName := filepath.Base(jarPath)
	logInfo("Embedding %s", jarName)
	if err := addFileToZip(zw, jarPath, jarName); err != nil {
		return nil, "", fmt.Errorf("embed JAR: %w", err)
	}

	logInfo("Embedding JRE")
	if err := addDirToZip(zw, jreDir, "jre"); err != nil {
		return nil, "", fmt.Errorf("embed JRE: %w", err)
	}

	if err := zw.Close(); err != nil {
		return nil, "", err
	}

	data := buf.Bytes()
	sum := fmt.Sprintf("%x", sha256.Sum256(data))
	return data, sum, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Runner template
// ─────────────────────────────────────────────────────────────────────────────

// runnerTemplate is the Go source code that gets compiled into the final binary.
// It embeds the payload zip and extracts it on first run.
const runnerTemplate = `// Code generated by jar2native. DO NOT EDIT.
package main

import (
	_ "embed"
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
)

//go:embed payload.zip
var payloadZip []byte

const payloadHash = "{{.Hash}}"
const jarName     = "{{.JarName}}"

func main() {
	dir, err := extractOnce()
	if err != nil {
		fmt.Fprintf(os.Stderr, "[ERROR] Failed to extract payload: %v\n", err)
		os.Exit(1)
	}

	javaExe := "java"
	if runtime.GOOS == "windows" {
		javaExe = "java.exe"
	}
	javaBin := filepath.Join(dir, "jre", "bin", javaExe)
	jarFile := filepath.Join(dir, jarName)

	cmd := exec.Command(javaBin, "-jar", jarFile)
	cmd.Args = append(cmd.Args, os.Args[1:]...)
	cmd.Stdin  = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			os.Exit(exitErr.ExitCode())
		}
		fmt.Fprintf(os.Stderr, "[ERROR] %v\n", err)
		os.Exit(1)
	}
}

// extractOnce extracts the payload zip to a stable cache directory.
// If the directory already exists (same hash), extraction is skipped.
func extractOnce() (string, error) {
	cacheDir, err := os.UserCacheDir()
	if err != nil {
		cacheDir = os.TempDir()
	}
	dir := filepath.Join(cacheDir, "jar2native", payloadHash)

	// Already extracted?
	if _, err := os.Stat(filepath.Join(dir, ".extracted")); err == nil {
		return dir, nil
	}

	fmt.Fprintln(os.Stderr, "[jar2native] First run: extracting runtime...")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}

	r, err := zip.NewReader(bytes.NewReader(payloadZip), int64(len(payloadZip)))
	if err != nil {
		return "", err
	}

	for _, f := range r.File {
		target := filepath.Join(dir, filepath.FromSlash(f.Name))

		if f.FileInfo().IsDir() {
			os.MkdirAll(target, 0755)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
			return "", err
		}

		rc, err := f.Open()
		if err != nil {
			return "", err
		}
		out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, f.Mode())
		if err != nil {
			rc.Close()
			return "", err
		}
		_, copyErr := io.Copy(out, rc)
		out.Close()
		rc.Close()
		if copyErr != nil {
			return "", copyErr
		}
	}

	// Mark as fully extracted
	marker, err := os.Create(filepath.Join(dir, ".extracted"))
	if err != nil {
		return "", err
	}
	marker.Close()

	return dir, nil
}
`

// ─────────────────────────────────────────────────────────────────────────────
// BinaryBuilder: generates a temp Go project and compiles it
// ─────────────────────────────────────────────────────────────────────────────

type runnerData struct {
	Hash    string
	JarName string
}

// BinaryBuilder compiles the final self-contained binary.
type BinaryBuilder struct {
	outputDir string
}

func NewBinaryBuilder(outputDir string) *BinaryBuilder {
	return &BinaryBuilder{outputDir: outputDir}
}

// Build generates a Go project in a temp dir, embeds the payload, and compiles.
// targetOS/targetArch are GOOS/GOARCH values (empty = current platform).
func (b *BinaryBuilder) Build(
	jarPath string,
	payloadData []byte,
	payloadHash string,
	outputName string,
	targetOS string,
	targetArch string,
) (string, error) {
	// ── Temp project directory ──────────────────────────────────────────────
	tmpDir, err := os.MkdirTemp("", "jar2native-runner-*")
	if err != nil {
		return "", fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	// ── Write payload.zip ───────────────────────────────────────────────────
	payloadPath := filepath.Join(tmpDir, "payload.zip")
	if err := os.WriteFile(payloadPath, payloadData, 0644); err != nil {
		return "", fmt.Errorf("write payload.zip: %w", err)
	}

	// ── Write main.go from template ─────────────────────────────────────────
	tmpl, err := template.New("runner").Parse(runnerTemplate)
	if err != nil {
		return "", fmt.Errorf("parse runner template: %w", err)
	}
	var mainBuf bytes.Buffer
	if err := tmpl.Execute(&mainBuf, runnerData{
		Hash:    payloadHash,
		JarName: filepath.Base(jarPath),
	}); err != nil {
		return "", fmt.Errorf("render runner template: %w", err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "main.go"), mainBuf.Bytes(), 0644); err != nil {
		return "", fmt.Errorf("write main.go: %w", err)
	}

	// ── Write go.mod ────────────────────────────────────────────────────────
	goMod := "module runner\n\ngo 1.21\n"
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0644); err != nil {
		return "", fmt.Errorf("write go.mod: %w", err)
	}

	// ── Determine output path (must be absolute; go build runs in tmpDir) ──
	absOutputDir, err := filepath.Abs(b.outputDir)
	if err != nil {
		return "", fmt.Errorf("resolve output dir: %w", err)
	}
	if err := os.MkdirAll(absOutputDir, 0755); err != nil {
		return "", fmt.Errorf("create output dir: %w", err)
	}
	outFile := filepath.Join(absOutputDir, outputName)
	if targetOS == "windows" {
		outFile += ".exe"
	}

	// ── Run go build ────────────────────────────────────────────────────────
	logStep("Compiling binary: %s", outFile)
	goBin, err := findGo()
	if err != nil {
		return "", err
	}

	cmd := exec.Command(goBin, "build", "-ldflags", "-s -w", "-o", outFile, ".")
	cmd.Dir = tmpDir
	cmd.Env = append(os.Environ(),
		"CGO_ENABLED=0",
	)
	if targetOS != "" {
		cmd.Env = append(cmd.Env, "GOOS="+targetOS)
	}
	if targetArch != "" {
		cmd.Env = append(cmd.Env, "GOARCH="+targetArch)
	}

	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("go build failed: %w\n%s", err, string(out))
	}

	logOK("Binary compiled: %s", outFile)
	return outFile, nil
}

// findGo locates the go binary.
func findGo() (string, error) {
	// Try PATH first
	if p, err := exec.LookPath("go"); err == nil {
		return p, nil
	}
	// Common install locations
	candidates := []string{
		"/opt/homebrew/bin/go",
		"/usr/local/go/bin/go",
		"/usr/bin/go",
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c, nil
		}
	}
	return "", fmt.Errorf("go binary not found; please install Go from https://go.dev/dl/")
}

// ─────────────────────────────────────────────────────────────────────────────
// JavaPackager: orchestrates the full workflow
// ─────────────────────────────────────────────────────────────────────────────

// JavaPackager orchestrates the full packaging workflow.
type JavaPackager struct {
	cfg *Config
	jdk *JDKManager
}

// NewJavaPackager creates a new JavaPackager from the given config.
func NewJavaPackager(cfg *Config) (*JavaPackager, error) {
	jdk, err := NewJDKManager(cfg.JDKPath)
	if err != nil {
		return nil, err
	}
	return &JavaPackager{cfg: cfg, jdk: jdk}, nil
}

// Package runs the full packaging workflow.
func (p *JavaPackager) Package() error {
	start := time.Now()

	jarPath, err := filepath.Abs(p.cfg.JarFile)
	if err != nil {
		return fmt.Errorf("invalid jar path: %w", err)
	}

	// ── Validate ────────────────────────────────────────────────────────────
	if err := p.validate(jarPath); err != nil {
		return err
	}

	// ── Prepare temp workspace ──────────────────────────────────────────────
	tmpDir, err := os.MkdirTemp("", "jar2native-*")
	if err != nil {
		return fmt.Errorf("failed to create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	jreDir := filepath.Join(tmpDir, "jre")

	if p.jdk.IsLegacy() {
		// ── Java 8 and below: copy the existing JRE, skip jdeps/jlink ───────
		logInfo("Java %d detected — using full JRE copy (jlink not available)", p.jdk.Version)
		if err := NewJREBuilder(p.jdk).Build(jreDir, ""); err != nil {
			return err
		}
	} else {
		// ── Java 9+: analyze modules then build minimal JRE with jlink ───────
		logStep("Analyzing module dependencies")
		analyzer := NewModuleAnalyzer(p.jdk)
		analyzed, err := analyzer.Analyze(jarPath, p.cfg.AllModules)
		if err != nil {
			return fmt.Errorf("module analysis failed: %w", err)
		}
		finalModules := MergeModules(analyzed, p.cfg.ExtraModules)
		logInfo("Final modules: %s", finalModules)

		if err := NewJREBuilder(p.jdk).Build(jreDir, finalModules); err != nil {
			return err
		}
	}

	// ── Build payload zip (JAR + JRE in memory) ─────────────────────────────
	logStep("Building payload (JAR + JRE)")
	payloadData, payloadHash, err := buildPayloadZip(jarPath, jreDir)
	if err != nil {
		return fmt.Errorf("build payload: %w", err)
	}
	logInfo("Payload size: %.1f MB  hash: %s…", float64(len(payloadData))/1e6, payloadHash[:12])

	// ── Compile final binary ────────────────────────────────────────────────
	appName := strings.TrimSuffix(filepath.Base(jarPath), filepath.Ext(jarPath))
	builder := NewBinaryBuilder("dist")

	outFile, err := builder.Build(
		jarPath,
		payloadData,
		payloadHash,
		appName,
		p.cfg.TargetOS,
		p.cfg.TargetArch,
	)
	if err != nil {
		return err
	}

	elapsed := time.Since(start)
	fmt.Printf("\n✅ Done in %.2fs\n", elapsed.Seconds())
	fmt.Printf("   Output : %s\n", outFile)
	fmt.Printf("   Size   : %.1f MB\n", float64(fileSize(outFile))/1e6)
	fmt.Println()
	fmt.Println("The binary is fully self-contained — just run it:")
	if p.cfg.TargetOS == "windows" {
		fmt.Printf("  %s.exe\n", appName)
	} else {
		fmt.Printf("  chmod +x dist/%s && dist/%s\n", appName, appName)
	}
	return nil
}

func fileSize(path string) int64 {
	info, err := os.Stat(path)
	if err != nil {
		return 0
	}
	return info.Size()
}

// validate checks that the input file exists and is a valid JAR/WAR.
func (p *JavaPackager) validate(jarPath string) error {
	if _, err := os.Stat(jarPath); os.IsNotExist(err) {
		return fmt.Errorf("input file not found: %s", jarPath)
	}

	ext := strings.ToLower(filepath.Ext(jarPath))
	if ext != ".jar" && ext != ".war" {
		return fmt.Errorf("only JAR and WAR files are supported")
	}

	if ext == ".jar" {
		if ok, err := hasMainClass(p.jdk, jarPath); err != nil || !ok {
			return fmt.Errorf("JAR file missing Main-Class attribute in MANIFEST.MF")
		}
	}
	return nil
}

// hasMainClass checks whether the JAR's MANIFEST.MF contains a Main-Class entry.
// It reads the zip directly — no external jar command needed.
func hasMainClass(_ *JDKManager, jarPath string) (bool, error) {
	r, err := zip.OpenReader(jarPath)
	if err != nil {
		return false, fmt.Errorf("open JAR: %w", err)
	}
	defer r.Close()

	for _, f := range r.File {
		if f.Name != "META-INF/MANIFEST.MF" {
			continue
		}
		rc, err := f.Open()
		if err != nil {
			return false, err
		}
		data, err := io.ReadAll(rc)
		rc.Close()
		if err != nil {
			return false, err
		}
		return strings.Contains(string(data), "Main-Class"), nil
	}
	return false, nil
}
